export const DEMO_SEED_VERSION = '2026-03-05';

export const DEMO_SEED_PAYLOAD = {
  "tasks": [
    {
      "id": 1,
      "name": "Phase 1 — Initiation & Discovery",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 25,
      "start": "2025-04-07",
      "pct": 100,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 2,
      "name": "Stakeholder identification & engagement",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 5,
      "start": "2025-04-07",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 3,
      "name": "Current network audit & inventory (42 sites)",
      "type": "Task",
      "parent": 2,
      "depType": "FS",
      "dur": 10,
      "start": "2025-04-14",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 4,
      "name": "Baseline performance benchmarking",
      "type": "Task",
      "parent": 3,
      "depType": "FS",
      "dur": 5,
      "start": "2025-04-28",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 5,
      "name": "Requirements gathering workshops",
      "type": "Task",
      "parent": 3,
      "depType": "FS",
      "dur": 5,
      "start": "2025-04-28",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 6,
      "name": "Discovery Complete — Gate 1",
      "type": "Milestone",
      "parent": 4,
      "depType": "FS",
      "dur": 0,
      "start": "2025-05-05",
      "pct": 100,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 7,
      "name": "Phase 2 — Architecture & Design",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 30,
      "start": "2025-05-12",
      "pct": 75,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 8,
      "name": "Target network topology design",
      "type": "Task",
      "parent": 6,
      "depType": "FS",
      "dur": 10,
      "start": "2025-05-05",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 9,
      "name": "SD-WAN overlay architecture",
      "type": "Task",
      "parent": 8,
      "depType": "FS",
      "dur": 8,
      "start": "2025-05-19",
      "pct": 100,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 10,
      "name": "Security policy & segmentation design",
      "type": "Task",
      "parent": 8,
      "depType": "FS",
      "dur": 8,
      "start": "2025-05-19",
      "pct": 80,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 11,
      "name": "QoS & traffic engineering model",
      "type": "Task",
      "parent": 9,
      "depType": "FS",
      "dur": 5,
      "start": "2025-05-29",
      "pct": 60,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 12,
      "name": "Cloud connectivity design (Azure/AWS)",
      "type": "Task",
      "parent": 9,
      "depType": "FS",
      "dur": 5,
      "start": "2025-05-29",
      "pct": 70,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 13,
      "name": "Vendor selection & procurement",
      "type": "Task",
      "parent": 8,
      "depType": "FS",
      "dur": 10,
      "start": "2025-05-19",
      "pct": 90,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 14,
      "name": "Design Sign-Off — Gate 2",
      "type": "Milestone",
      "parent": 11,
      "depType": "FS",
      "dur": 0,
      "start": "2025-06-05",
      "pct": 0,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 15,
      "name": "Phase 3 — Lab Testing & Pilot",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 35,
      "start": "2025-06-30",
      "pct": 30,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 16,
      "name": "Lab environment build",
      "type": "Task",
      "parent": 14,
      "depType": "FS",
      "dur": 5,
      "start": "2025-06-05",
      "pct": 80,
      "indent": 1,
      "tracked": true
    },
    {
      "id": 17,
      "name": "Configuration templates & automation",
      "type": "Task",
      "parent": 16,
      "depType": "FS",
      "dur": 8,
      "start": "2025-06-12",
      "pct": 50,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 18,
      "name": "Lab integration testing",
      "type": "Task",
      "parent": 17,
      "depType": "FS",
      "dur": 10,
      "start": "2025-06-24",
      "pct": 20,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 19,
      "name": "Pilot site selection & preparation",
      "type": "Task",
      "parent": 16,
      "depType": "FS",
      "dur": 3,
      "start": "2025-06-12",
      "pct": 60,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 20,
      "name": "Pilot deployment (Manchester & Edinburgh)",
      "type": "Task",
      "parent": 18,
      "depType": "FS",
      "dur": 10,
      "start": "2025-07-08",
      "pct": 10,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 21,
      "name": "Pilot validation & lessons learned",
      "type": "Task",
      "parent": 20,
      "depType": "FS",
      "dur": 5,
      "start": "2025-07-22",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 22,
      "name": "Pilot Approved — Gate 3",
      "type": "Milestone",
      "parent": 21,
      "depType": "FS",
      "dur": 0,
      "start": "2025-07-29",
      "pct": 0,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 23,
      "name": "Phase 4 — Phased Rollout",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 60,
      "start": "2025-09-01",
      "pct": 0,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 24,
      "name": "Wave 1 — Regional HQ sites (5 sites)",
      "type": "Task",
      "parent": 22,
      "depType": "FS",
      "dur": 15,
      "start": "2025-07-29",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 25,
      "name": "Wave 2 — Branch offices (20 sites)",
      "type": "Task",
      "parent": 24,
      "depType": "FS",
      "dur": 20,
      "start": "2025-08-19",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 26,
      "name": "Wave 3 — Remote & satellite (15 sites)",
      "type": "Task",
      "parent": 25,
      "depType": "FS",
      "dur": 15,
      "start": "2025-09-16",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 27,
      "name": "Legacy MPLS decommission (phased)",
      "type": "Task",
      "parent": 26,
      "depType": "FS",
      "dur": 10,
      "start": "2025-10-07",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 28,
      "name": "Rollout Complete — Gate 4",
      "type": "Milestone",
      "parent": 27,
      "depType": "FS",
      "dur": 0,
      "start": "2025-10-21",
      "pct": 0,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 29,
      "name": "Phase 5 — Optimisation & BAU Handover",
      "type": "Task",
      "parent": null,
      "depType": "FS",
      "dur": 25,
      "start": "2025-12-01",
      "pct": 0,
      "indent": 0,
      "tracked": false
    },
    {
      "id": 30,
      "name": "Performance tuning & QoS optimisation",
      "type": "Task",
      "parent": 28,
      "depType": "FS",
      "dur": 10,
      "start": "2025-10-21",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 31,
      "name": "Monitoring & alerting setup (PRTG/Zabbix)",
      "type": "Task",
      "parent": 28,
      "depType": "FS",
      "dur": 5,
      "start": "2025-10-21",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 32,
      "name": "Documentation & runbooks",
      "type": "Task",
      "parent": 30,
      "depType": "FS",
      "dur": 8,
      "start": "2025-11-04",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 33,
      "name": "Knowledge transfer to BAU team",
      "type": "Task",
      "parent": 32,
      "depType": "FS",
      "dur": 5,
      "start": "2025-11-14",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 34,
      "name": "Post-migration review & benefits realisation",
      "type": "Task",
      "parent": 33,
      "depType": "FS",
      "dur": 5,
      "start": "2025-11-21",
      "pct": 0,
      "indent": 1,
      "tracked": false
    },
    {
      "id": 35,
      "name": "Project Closure — Gate 5",
      "type": "Milestone",
      "parent": 34,
      "depType": "FS",
      "dur": 0,
      "start": "2025-11-28",
      "pct": 0,
      "indent": 0,
      "tracked": false
    }
  ],
  "registers": {
    "risks": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "category": "Technical",
        "riskdetails": "MPLS-to-SD-WAN cutover causes extended downtime at critical sites",
        "mitigatingaction": "Phased migration with parallel running; rollback tested in lab",
        "notes": "Priority sites have 4hr SLA",
        "raised": "2025-04-14",
        "owner": "Network Architect",
        "level": "High"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "category": "Vendor",
        "riskdetails": "SD-WAN vendor unable to deliver hardware within lead times",
        "mitigatingaction": "Early PO placement; identify secondary supplier; consider virtual CPE",
        "notes": "Lead time 8-12 weeks",
        "raised": "2025-04-21",
        "owner": "Procurement Lead",
        "level": "High"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "category": "Security",
        "riskdetails": "New network topology introduces unplanned attack surface",
        "mitigatingaction": "Security review at each gate; penetration testing before pilot",
        "notes": "",
        "raised": "2025-04-21",
        "owner": "Security Lead",
        "level": "Medium"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "category": "Resource",
        "riskdetails": "Key network architect unavailable during rollout phase",
        "mitigatingaction": "Cross-train two engineers; document all design decisions",
        "notes": "Contractor backup identified",
        "raised": "2025-04-28",
        "owner": "Programme Manager",
        "level": "Medium"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "category": "Commercial",
        "riskdetails": "MPLS contract exit penalties higher than budgeted",
        "mitigatingaction": "Early engagement with carrier; legal review of break clauses",
        "notes": "Contract review week 3",
        "raised": "2025-04-14",
        "owner": "Commercial Manager",
        "level": "Medium"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "category": "Operational",
        "riskdetails": "BAU team lacks SD-WAN skills for post-migration support",
        "mitigatingaction": "Training plan in Phase 5; vendor support contract for Year 1",
        "notes": "",
        "raised": "2025-05-05",
        "owner": "Service Manager",
        "level": "Medium"
      },
      {
        "_id": "7",
        "number": "7",
        "visible": true,
        "public": true,
        "category": "Integration",
        "riskdetails": "Cloud connectivity (Azure ExpressRoute / AWS DX) delays",
        "mitigatingaction": "Parallel workstream for cloud provisioning; VPN fallback ready",
        "notes": "",
        "raised": "2025-05-12",
        "owner": "Cloud Architect",
        "level": "Low"
      },
      {
        "_id": "8",
        "number": "8",
        "visible": true,
        "public": false,
        "category": "Compliance",
        "riskdetails": "Data sovereignty requirements conflict with traffic routing",
        "mitigatingaction": "Geo-routing policies in SD-WAN; legal sign-off on data flows",
        "notes": "Affects EU branches",
        "raised": "2025-04-28",
        "owner": "Security Lead",
        "level": "High"
      }
    ],
    "issues": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "category": "Technical",
        "issueassignedto": "Network Architect",
        "description": "Legacy firewall rules not documented — blocking design",
        "currentstatus": "Reverse-engineering rules from packet captures",
        "status": "Open",
        "raised": "2025-04-21",
        "target": "2025-05-12",
        "completed": "",
        "update": "2025-05-05"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "category": "Commercial",
        "issueassignedto": "Procurement Lead",
        "description": "Preferred SD-WAN vendor pricing 18% over budget",
        "currentstatus": "Negotiating volume discount; evaluating Versa alternative",
        "status": "Open",
        "raised": "2025-04-28",
        "target": "2025-05-19",
        "completed": "",
        "update": "2025-05-12"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "category": "Resource",
        "issueassignedto": "Programme Manager",
        "description": "Network engineer resigned — single point of failure",
        "currentstatus": "Contractor engaged; knowledge transfer in progress",
        "status": "Open",
        "raised": "2025-05-05",
        "target": "2025-05-26",
        "completed": "",
        "update": "2025-05-12"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "category": "Facility",
        "issueassignedto": "Deployment Lead",
        "description": "Two branch sites have inadequate rack space for new CPE",
        "currentstatus": "Site surveys ordered; wall-mount CPE option being evaluated",
        "status": "Open",
        "raised": "2025-05-12",
        "target": "2025-06-02",
        "completed": "",
        "update": "2025-05-19"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": false,
        "category": "Integration",
        "issueassignedto": "Cloud Architect",
        "description": "Azure ExpressRoute provisioning delayed by 3 weeks",
        "currentstatus": "Escalated with Microsoft TAM; VPN interim solution deployed",
        "status": "Mitigated",
        "raised": "2025-05-19",
        "target": "2025-06-09",
        "completed": "",
        "update": "2025-05-26"
      }
    ],
    "actions": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "actionassignedto": "Network Architect",
        "description": "Complete current-state network topology diagram (all 42 sites)",
        "currentstatus": "",
        "status": "Completed",
        "raised": "",
        "target": "2025-04-21",
        "completed": ""
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "actionassignedto": "Commercial Manager",
        "description": "Obtain MPLS contract break clause terms from legal",
        "currentstatus": "",
        "status": "Completed",
        "raised": "",
        "target": "2025-04-28",
        "completed": ""
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "actionassignedto": "Procurement Lead",
        "description": "Issue RFP to shortlisted SD-WAN vendors (Fortinet, Cisco, Versa)",
        "currentstatus": "",
        "status": "Completed",
        "raised": "",
        "target": "2025-05-05",
        "completed": ""
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "actionassignedto": "Deployment Lead",
        "description": "Book pilot site visits — Manchester & Edinburgh offices",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-05-19",
        "completed": ""
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "actionassignedto": "Security Lead",
        "description": "Finalise security segmentation policy with CISO",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-05-26",
        "completed": ""
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "actionassignedto": "Procurement Lead",
        "description": "Procure lab equipment for integration testing",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-06-02",
        "completed": ""
      },
      {
        "_id": "7",
        "number": "7",
        "visible": true,
        "public": true,
        "actionassignedto": "Network Engineer",
        "description": "Develop rollback runbook and test in lab environment",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-06-16",
        "completed": ""
      },
      {
        "_id": "8",
        "number": "8",
        "visible": true,
        "public": true,
        "actionassignedto": "Service Manager",
        "description": "Schedule knowledge transfer sessions with BAU NOC team",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-12-08",
        "completed": ""
      },
      {
        "_id": "9",
        "number": "9",
        "visible": true,
        "public": false,
        "actionassignedto": "Security Lead",
        "description": "Confirm data sovereignty routing rules with legal counsel",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-05-12",
        "completed": ""
      },
      {
        "_id": "10",
        "number": "10",
        "visible": true,
        "public": true,
        "actionassignedto": "NOC Lead",
        "description": "Set up PRTG/Zabbix monitoring templates for SD-WAN overlay",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-12-01",
        "completed": ""
      },
      {
        "_id": "11",
        "number": "11",
        "visible": true,
        "public": true,
        "actionassignedto": "Programme Manager",
        "description": "Draft comms to office managers re: migration schedule",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-08-25",
        "completed": ""
      },
      {
        "_id": "12",
        "number": "12",
        "visible": true,
        "public": true,
        "actionassignedto": "Service Manager",
        "description": "Arrange vendor SD-WAN training for 6 BAU engineers",
        "currentstatus": "",
        "status": "Open",
        "raised": "",
        "target": "2025-12-15",
        "completed": ""
      },
      {
        "_id": "Lnk",
        "number": "Lnk",
        "visible": true,
        "public": true,
        "actionassignedto": "PM",
        "description": "Lab environment build",
        "currentstatus": "Tracked from Project Plan",
        "status": "In Progress",
        "raised": "2025-06-05",
        "target": "2025-06-12",
        "completed": ""
      }
    ],
    "changes": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "category": "Scope",
        "assignedto": "Network Architect",
        "description": "Add redundant internet circuits at 3 critical sites",
        "impactstatus": "£45K additional; +5 days Wave 1",
        "status": "Approved",
        "raised": "2025-05-19",
        "target": "2025-06-02",
        "updated": "2025-05-26",
        "complete": "2025-06-02"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "category": "Technical",
        "assignedto": "Cloud Architect",
        "description": "Include Azure ExpressRoute in design (originally VPN-only)",
        "impactstatus": "£18K/yr recurring; +3 days design",
        "status": "Approved",
        "raised": "2025-05-26",
        "target": "2025-06-09",
        "updated": "2025-06-02",
        "complete": "2025-06-09"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "category": "Scope",
        "assignedto": "Test Manager",
        "description": "Extend pilot from 1 site to 2 sites",
        "impactstatus": "£6K additional; +5 days pilot",
        "status": "Approved",
        "raised": "2025-06-02",
        "target": "2025-06-16",
        "updated": "2025-06-09",
        "complete": "2025-06-16"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "category": "Scope",
        "assignedto": "CTO",
        "description": "Add Wi-Fi 6 AP refresh to Wave 2 branch sites",
        "impactstatus": "£92K + 10 days; requires AP procurement",
        "status": "Under Review",
        "raised": "2025-06-16",
        "target": "2025-06-30",
        "updated": "2025-06-23",
        "complete": ""
      }
    ],
    "minutes": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "dateraised": "2025-04-14",
        "minutedescription": "Kick-off meeting. Scope confirmed: 42 sites MPLS-to-SD-WAN migration. Budget £1.2M. Timeline 9 months. Steering committee fortnightly.",
        "status": "Closed"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "dateraised": "2025-04-21",
        "minutedescription": "Discovery workshop #1. Manchester, Edinburgh, London HQ audited. 3 sites flagged with rack space constraints. Vendor shortlist agreed.",
        "status": "Closed"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "dateraised": "2025-04-28",
        "minutedescription": "Vendor shortlist: Fortinet, Cisco Viptela, Versa Networks. RFP to be issued by end of week 4. Baseline metrics captured.",
        "status": "Closed"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "dateraised": "2025-05-05",
        "minutedescription": "Gate 1 review: Discovery phase signed off. All 42 site audits complete. Baseline metrics captured.",
        "status": "Closed"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "dateraised": "2025-05-12",
        "minutedescription": "Design kick-off. Three topology options presented. Option B (hub-and-spoke with regional breakout) preferred.",
        "status": "Closed"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "dateraised": "2025-05-26",
        "minutedescription": "Security review with CISO. Zero-trust segmentation approach agreed. Pen test to be scheduled for pilot phase.",
        "status": "Closed"
      },
      {
        "_id": "7",
        "number": "7",
        "visible": true,
        "public": true,
        "dateraised": "2025-06-02",
        "minutedescription": "Vendor evaluation complete. Fortinet selected. PO raised for 50x FortiGate CPE units + FortiManager.",
        "status": "Closed"
      },
      {
        "_id": "8",
        "number": "8",
        "visible": true,
        "public": true,
        "dateraised": "2025-06-09",
        "minutedescription": "CR-001 approved: redundant internet at 3 critical sites. Budget impact £45K approved by CFO.",
        "status": "Closed"
      },
      {
        "_id": "9",
        "number": "9",
        "visible": true,
        "public": true,
        "dateraised": "2025-06-16",
        "minutedescription": "Lab build complete. Integration testing starting. Two automation scripts still in development.",
        "status": "Open"
      },
      {
        "_id": "10",
        "number": "10",
        "visible": true,
        "public": true,
        "dateraised": "2025-06-23",
        "minutedescription": "Steering committee: Gate 2 design sign-off pending QoS model. Expected next week.",
        "status": "Open"
      },
      {
        "_id": "11",
        "number": "11",
        "visible": true,
        "public": true,
        "dateraised": "2025-06-30",
        "minutedescription": "Pilot prep. Manchester (leased line) and Edinburgh (broadband) confirmed as pilot sites.",
        "status": "Open"
      },
      {
        "_id": "12",
        "number": "12",
        "visible": true,
        "public": true,
        "dateraised": "2025-07-07",
        "minutedescription": "CR-004 raised by CTO: Wi-Fi 6 AP refresh for Wave 2. Under review — £92K impact.",
        "status": "Open"
      }
    ],
    "costs": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "costdescription": "Fortinet FortiGate 60F CPE units (50x)",
        "dateraised": "2025-06-02",
        "sitename": "All sites",
        "cost": "£187,500",
        "tobechargedto": "Capital — IT Infrastructure",
        "acceptedby": "Catherine Moore",
        "date": "2025-06-09",
        "billing": "One-off"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "costdescription": "FortiManager centralised management licence (3yr)",
        "dateraised": "2025-06-02",
        "sitename": "London HQ",
        "cost": "£24,000",
        "tobechargedto": "Capital — IT Infrastructure",
        "acceptedby": "Catherine Moore",
        "date": "2025-06-09",
        "billing": "Annual"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "costdescription": "Lab environment build (switches, cabling, rack)",
        "dateraised": "2025-06-30",
        "sitename": "London Lab",
        "cost": "£8,500",
        "tobechargedto": "Capital — IT Infrastructure",
        "acceptedby": "James Whitfield",
        "date": "2025-06-30",
        "billing": "One-off"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "costdescription": "Azure ExpressRoute provisioning (CR-002)",
        "dateraised": "2025-05-26",
        "sitename": "London HQ",
        "cost": "£18,000",
        "tobechargedto": "Opex — Cloud Services",
        "acceptedby": "Richard Halsey",
        "date": "2025-06-09",
        "billing": "Annual"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "costdescription": "Redundant internet circuits x3 (CR-001)",
        "dateraised": "2025-05-19",
        "sitename": "LDN/MAN/EDI",
        "cost": "£45,000",
        "tobechargedto": "Capital — IT Infrastructure",
        "acceptedby": "Richard Halsey",
        "date": "2025-06-02",
        "billing": "One-off"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "costdescription": "BT MPLS early termination fee (estimated)",
        "dateraised": "2025-04-14",
        "sitename": "All sites",
        "cost": "£62,000",
        "tobechargedto": "Opex — Telecoms",
        "acceptedby": "Richard Halsey",
        "date": "",
        "billing": "One-off"
      },
      {
        "_id": "7",
        "number": "7",
        "visible": true,
        "public": true,
        "costdescription": "Contractor network engineer (3 months)",
        "dateraised": "2025-05-05",
        "sitename": "London HQ",
        "cost": "£36,000",
        "tobechargedto": "Opex — Professional Services",
        "acceptedby": "James Whitfield",
        "date": "2025-05-12",
        "billing": "Monthly"
      },
      {
        "_id": "8",
        "number": "8",
        "visible": true,
        "public": true,
        "costdescription": "Zscaler Internet Access licences (42 sites, 3yr)",
        "dateraised": "2025-06-09",
        "sitename": "All sites",
        "cost": "£54,000",
        "tobechargedto": "Opex — Security",
        "acceptedby": "David Okonkwo",
        "date": "2025-06-16",
        "billing": "Annual"
      },
      {
        "_id": "9",
        "number": "9",
        "visible": true,
        "public": true,
        "costdescription": "PRTG monitoring licences (500 sensors)",
        "dateraised": "2025-12-01",
        "sitename": "London NOC",
        "cost": "£4,200",
        "tobechargedto": "Opex — IT Tools",
        "acceptedby": "Priya Sharma",
        "date": "",
        "billing": "Annual"
      },
      {
        "_id": "10",
        "number": "10",
        "visible": true,
        "public": true,
        "costdescription": "Vendor SD-WAN training (6 engineers, 5 days)",
        "dateraised": "2025-12-15",
        "sitename": "London HQ",
        "cost": "£9,600",
        "tobechargedto": "Opex — Training",
        "acceptedby": "Priya Sharma",
        "date": "",
        "billing": "One-off"
      }
    ],
    "stakeholders": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "name": "Catherine Moore",
        "organisation": "NorthStar Retail Group",
        "role": "CIO (Programme Sponsor)",
        "email": "catherine.moore@northstar.example",
        "phone": "+44 20 7000 1001",
        "mobile": "+44 7700 100101",
        "escalationlevel": "Executive"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "name": "Rahul Sharma",
        "organisation": "NorthStar Retail Group",
        "role": "Programme Director",
        "email": "rahul.sharma@northstar.example",
        "phone": "+44 20 7000 1002",
        "mobile": "+44 7700 100102",
        "escalationlevel": "Executive"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "name": "Priya Nair",
        "organisation": "NorthStar Retail Group",
        "role": "Lead Network Architect",
        "email": "priya.nair@northstar.example",
        "phone": "+44 20 7000 1003",
        "mobile": "+44 7700 100103",
        "escalationlevel": "Design Authority"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "name": "Daniel Cruz",
        "organisation": "NorthStar Retail Group",
        "role": "Security Lead",
        "email": "daniel.cruz@northstar.example",
        "phone": "+44 20 7000 1004",
        "mobile": "+44 7700 100104",
        "escalationlevel": "Design Authority"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "name": "Olivia Green",
        "organisation": "NetWave Delivery",
        "role": "Service Delivery Manager",
        "email": "olivia.green@netwave.example",
        "phone": "+44 20 7000 1005",
        "mobile": "+44 7700 100105",
        "escalationlevel": "Operational"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "name": "Mark Evans",
        "organisation": "Carrier One",
        "role": "Carrier Delivery Lead",
        "email": "mark.evans@carrierone.example",
        "phone": "+44 20 7000 1006",
        "mobile": "+44 7700 100106",
        "escalationlevel": "Operational"
      },
      {
        "_id": "7",
        "number": "7",
        "visible": true,
        "public": true,
        "name": "Helen Brooks",
        "organisation": "NorthStar Retail Group",
        "role": "CAB Chair",
        "email": "helen.brooks@northstar.example",
        "phone": "+44 20 7000 1007",
        "mobile": "+44 7700 100107",
        "escalationlevel": "Governance"
      },
      {
        "_id": "8",
        "number": "8",
        "visible": true,
        "public": true,
        "name": "Tom Bennett",
        "organisation": "NorthStar Retail Group",
        "role": "Site Operations Lead",
        "email": "tom.bennett@northstar.example",
        "phone": "+44 20 7000 1008",
        "mobile": "+44 7700 100108",
        "escalationlevel": "Operational"
      }
    ],
    "commsplan": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "audience": "Steering Committee",
        "meetingtype": "SteerCo",
        "informationrequired": "Overall RAG, budget variance, top 3 risks/issues",
        "frequency": "Weekly",
        "daytime": "Tuesday 10:00",
        "method": "Video call + deck",
        "owner": "Programme Director",
        "template": "SteerCo Pack v3"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "audience": "PMO + Workstream Leads",
        "meetingtype": "Delivery Stand-up",
        "informationrequired": "Previous-day progress, blockers, 48-hour plan",
        "frequency": "Daily (Weekdays)",
        "daytime": "09:00",
        "method": "Teams call",
        "owner": "Project Manager",
        "template": "Daily Stand-up Template"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "audience": "CAB",
        "meetingtype": "Change Advisory Board",
        "informationrequired": "Planned changes, risk assessment, rollback readiness",
        "frequency": "Weekly",
        "daytime": "Thursday 14:00",
        "method": "CAB portal + meeting",
        "owner": "CAB Chair",
        "template": "CAB Submission Form"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "audience": "Site Managers (Wave 1-4)",
        "meetingtype": "Cutover Readiness Briefing",
        "informationrequired": "Cutover checklist, downtime windows, onsite contacts",
        "frequency": "Per wave",
        "daytime": "72h + 24h pre-cutover",
        "method": "Email + briefing call",
        "owner": "Deployment Lead",
        "template": "Wave Readiness Checklist"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "audience": "Operations + NOC",
        "meetingtype": "Hypercare Bridge",
        "informationrequired": "Incident trend, SLA compliance, open actions",
        "frequency": "Daily (Hypercare)",
        "daytime": "08:30",
        "method": "Bridge call",
        "owner": "Service Delivery Manager",
        "template": "Hypercare Dashboard"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "audience": "Executive Sponsor",
        "meetingtype": "Escalation Brief",
        "informationrequired": "Critical issue summary, impact, decision required",
        "frequency": "Ad hoc",
        "daytime": "Within 4h of trigger",
        "method": "Phone + email summary",
        "owner": "Programme Director",
        "template": "Critical Escalation Note"
      }
    ],
    "assumptions": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "type": "Assumption",
        "description": "All 42 sites will provide approved access windows for migration activities.",
        "raisedby": "Project Manager",
        "dateraised": "2025-04-10",
        "impact": "Schedule",
        "status": "Validated",
        "validationnotes": "Confirmed by regional ops leads for Wave 1 and Wave 2.",
        "owner": "Deployment Lead"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "type": "Dependency",
        "description": "Carrier delivers upgraded circuits before each wave cutover date.",
        "raisedby": "Service Delivery Manager",
        "dateraised": "2025-04-14",
        "impact": "Schedule / Service Risk",
        "status": "At Risk",
        "validationnotes": "2 sites still showing provisional RFS; escalation open.",
        "owner": "Carrier Delivery Lead"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "type": "Dependency",
        "description": "Identity team completes SSO federation for SD-WAN orchestrator access.",
        "raisedby": "Security Lead",
        "dateraised": "2025-04-18",
        "impact": "Operational Readiness",
        "status": "Open",
        "validationnotes": "Target completion aligned to design sign-off gate.",
        "owner": "IAM Product Owner"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "type": "Assumption",
        "description": "Firewall policy clean-up can be completed without additional tooling.",
        "raisedby": "Network Architect",
        "dateraised": "2025-04-22",
        "impact": "Design / Effort",
        "status": "Needs Review",
        "validationnotes": "May require temporary external review support.",
        "owner": "Security Lead"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "type": "Dependency",
        "description": "Change freeze windows approved by business units during peak season.",
        "raisedby": "CAB Chair",
        "dateraised": "2025-05-02",
        "impact": "Schedule",
        "status": "Open",
        "validationnotes": "Commercial division sign-off pending.",
        "owner": "PMO"
      },
      {
        "_id": "6",
        "number": "6",
        "visible": true,
        "public": true,
        "type": "Assumption",
        "description": "Operations team will provide 24x7 hypercare staffing for first two waves.",
        "raisedby": "Service Manager",
        "dateraised": "2025-05-12",
        "impact": "Service Stability",
        "status": "Validated",
        "validationnotes": "Rota agreed and budget approved.",
        "owner": "Service Delivery Manager"
      },
      {
        "_id": "assumption_seed_1772743529392_1",
        "number": 7,
        "visible": true,
        "public": true,
        "type": "Assumption",
        "description": "Service desk is available for Wave 3 cutover nights.",
        "raisedby": "Project Manager",
        "dateraised": "2025-08-05",
        "impact": "Operational readiness",
        "status": "Validated",
        "validationnotes": "Rota and escalation contacts confirmed by CAB-2.",
        "owner": "Project Manager"
      }
    ],
    "decisions": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "decision": "Adopt dual-underlay (MPLS + DIA) design for all core and priority sites.",
        "decidedby": "Design Authority Board",
        "dateraised": "2025-04-15",
        "datedecided": "2025-04-22",
        "rationale": "Improves resilience and enables phased migration with rollback safety.",
        "impact": "Higher circuit cost, lower outage risk",
        "status": "Approved"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "decision": "Standardize on Fortinet 60F for branch CPE footprint.",
        "decidedby": "Architecture Review Board",
        "dateraised": "2025-04-20",
        "datedecided": "2025-04-28",
        "rationale": "Operational consistency, integrated security stack, existing team skills.",
        "impact": "Simplified support model",
        "status": "Approved"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "decision": "Execute migration in four regional waves rather than site-by-site sequence.",
        "decidedby": "Programme Steering Committee",
        "dateraised": "2025-05-01",
        "datedecided": "2025-05-06",
        "rationale": "Reduces coordination overhead and compresses delivery timeline.",
        "impact": "Requires tighter wave readiness governance",
        "status": "Approved"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "decision": "Enable direct internet breakout for low-risk SaaS traffic at branch sites.",
        "decidedby": "Security and Network Leads",
        "dateraised": "2025-05-10",
        "datedecided": "2025-05-16",
        "rationale": "Improves performance and reduces backhaul load.",
        "impact": "Requires updated security policy controls",
        "status": "Approved with Conditions"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "decision": "Set hypercare period to 30 days after each wave completion.",
        "decidedby": "Service Transition Board",
        "dateraised": "2025-05-20",
        "datedecided": "2025-05-24",
        "rationale": "Ensures stable operations and knowledge transfer to BAU.",
        "impact": "Extends support staffing window",
        "status": "Approved"
      },
      {
        "_id": "decision_seed_1772743529392_1",
        "number": 6,
        "visible": true,
        "public": true,
        "decision": "Use a single change freeze calendar across all migration waves.",
        "decidedby": "Programme Board",
        "dateraised": "2025-08-07",
        "datedecided": "2025-08-12",
        "rationale": "Prevents conflicting production changes during network cutovers.",
        "impact": "Lower operational risk",
        "status": "Approved"
      }
    ],
    "lessons": [
      {
        "_id": "1",
        "number": "1",
        "visible": true,
        "public": true,
        "date": "2025-06-03",
        "phase": "Pilot Cutover",
        "category": "Readiness",
        "description": "Site readiness packs were inconsistent across pilot locations.",
        "whatwentwell": "Checklist structure was useful once completed.",
        "whatcouldimprove": "Mandate minimum evidence set before CAB submission.",
        "recommendation": "Introduce readiness quality gate 5 business days before cutover.",
        "owner": "PMO",
        "status": "Implemented"
      },
      {
        "_id": "2",
        "number": "2",
        "visible": true,
        "public": true,
        "date": "2025-06-10",
        "phase": "Pilot Hypercare",
        "category": "Incident Management",
        "description": "L1 support lacked clear routing guidance for SD-WAN alarms.",
        "whatwentwell": "Escalation path to L3 was quick.",
        "whatcouldimprove": "L1 troubleshooting script needs SD-WAN specific steps.",
        "recommendation": "Publish L1 runbook and train service desk before Wave 2.",
        "owner": "Service Manager",
        "status": "In Progress"
      },
      {
        "_id": "3",
        "number": "3",
        "visible": true,
        "public": true,
        "date": "2025-06-18",
        "phase": "Wave 1 Preparation",
        "category": "Dependency Management",
        "description": "Carrier RFS dates changed late for two sites.",
        "whatwentwell": "Escalation governance prevented full wave delay.",
        "whatcouldimprove": "Earlier visibility of carrier confidence levels.",
        "recommendation": "Track carrier milestone confidence in weekly risk review.",
        "owner": "Carrier Delivery Lead",
        "status": "Open"
      },
      {
        "_id": "4",
        "number": "4",
        "visible": true,
        "public": true,
        "date": "2025-06-24",
        "phase": "Change Governance",
        "category": "Governance",
        "description": "CAB submissions varied in rollback detail quality.",
        "whatwentwell": "Template helped standardize high-level sections.",
        "whatcouldimprove": "Rollback section still too brief in some submissions.",
        "recommendation": "Make rollback evidence mandatory field in CAB template.",
        "owner": "CAB Chair",
        "status": "Implemented"
      },
      {
        "_id": "5",
        "number": "5",
        "visible": true,
        "public": true,
        "date": "2025-07-01",
        "phase": "Wave 1 Cutover",
        "category": "Communication",
        "description": "Business units appreciated clearer outage-window comms.",
        "whatwentwell": "72h and 24h reminder cadence reduced escalations.",
        "whatcouldimprove": "Need localized comms for non-UK branches.",
        "recommendation": "Add regional communication variants to comms plan.",
        "owner": "Project Manager",
        "status": "In Progress"
      },
      {
        "_id": "lesson_seed_1772743529392_1",
        "number": 6,
        "visible": true,
        "public": true,
        "date": "2025-08-19",
        "phase": "Wave Planning",
        "category": "Governance",
        "description": "Cross-team handoff quality improved after pre-wave dry runs.",
        "whatwentwell": "Ownership was clear and defect triage was faster.",
        "whatcouldimprove": "Dependency updates were sometimes posted too late.",
        "recommendation": "Publish readiness checklist sign-off 48h before each wave.",
        "owner": "PMO",
        "status": "In Progress"
      }
    ],
    "_raci": [
      {
        "roles": [
          "Project Manager",
          "Technical Architect",
          "Delivery Lead",
          "PMO Lead",
          "Business Sponsor"
        ],
        "assignments": {
          "_customTasks": [
            "Project plan"
          ],
          "custom-0::Project Manager": "R",
          "custom-0::Technical Architect": "C"
        },
        "updatedAt": "2026-03-05T00:00:00.000Z"
      }
    ]
  },
  "tracker": [
    {
      "_id": "tracker_seed_1",
      "taskId": 24,
      "taskName": "Wave 1 — Regional HQ sites (5 sites)",
      "notes": "3/2 - Test",
      "status": "Not Started",
      "rag": "Green",
      "nextAction": "",
      "owner": "",
      "dateAdded": "2026-03-05",
      "lastUpdated": "2026-03-05"
    },
    {
      "_id": "tracker_seed_2",
      "taskId": 25,
      "taskName": "Wave 2 — Branch offices (20 sites)",
      "notes": "",
      "status": "Not Started",
      "rag": "Green",
      "nextAction": "",
      "owner": "",
      "dateAdded": "2026-03-05",
      "lastUpdated": "2026-03-05"
    }
  ],
  "status_report": {
    "overallRag": "Green",
    "overallNarrative": "The project made significant progress this period, successfully completing Phase 1 — Initiation & Discovery, along with related key milestones such as Stakeholder identification & engagement, and Discovery Complete — Gate 1. This marks a critical step forward in the project lifecycle. However, the project continues to manage multiple high and medium severity risks. Additionally, several open medium-severity issues require ongoing attention, including challenges with legacy firewall documentation and vendor pricing.",
    "mainRisks": "",
    "mainIssues": "",
    "deliverablesThisPeriod": "",
    "deliverablesNextPeriod": "",
    "additionalNotes": ""
  },
  "baseline": null
};

export const cloneDemoSeedPayload = () => {
  if (typeof structuredClone === 'function') {
    return structuredClone(DEMO_SEED_PAYLOAD);
  }
  return JSON.parse(JSON.stringify(DEMO_SEED_PAYLOAD));
};
